#!/bin/sh
BASEDIR=$(cd "$(dirname "$0")"; pwd)

cd $BASEDIR;
git submodule init;
git submodule update;

ln -svF $BASEDIR/.gitconfig $HOME;
ln -svF $BASEDIR/.screenrc $HOME;
ln -svF $BASEDIR/.vim $HOME;
ln -svF $BASEDIR/.vimrc $HOME;
ln -svF $BASEDIR/.CFUserTextEncoding $HOME;

echo "
The C extension must then be built, which can be done from the shell. If you
use a typical |'runtimepath'| then the files were installed inside ~/.vim and
you can build the extension with:

  cd ~/.vim/bundle/command-t/ruby/command-t
  ruby extconf.rb
  make

Note: If you are an RVM or rbenv user, you must perform the build using the
same version of Ruby that Vim itself is linked against. This will often be the
system Ruby, which can be selected before issuing the "make" command with one
of the following commands:

  rvm use system
  rbenv local system
"
